// AUTO-GENERATED by scripts/voice/generate-all.ts — do not edit by hand.
// Run `pnpm voice:generate` to refresh after changing the manifest.
import ch1_s11_aether_01 from "../../assets/voice/ch1/ch1_s11_aether_01.mp3?url";
import ch1_s11_aether_02 from "../../assets/voice/ch1/ch1_s11_aether_02.mp3?url";
import ch1_s12a_aether_01 from "../../assets/voice/ch1/ch1_s12a_aether_01.mp3?url";
import ch1_s12a_aether_02 from "../../assets/voice/ch1/ch1_s12a_aether_02.mp3?url";
import ch1_s12a2_aether_01 from "../../assets/voice/ch1/ch1_s12a2_aether_01.mp3?url";
import ch1_s12a2_aether_02 from "../../assets/voice/ch1/ch1_s12a2_aether_02.mp3?url";
import ch1_s12c_aether_01 from "../../assets/voice/ch1/ch1_s12c_aether_01.mp3?url";
import ch1_s13_aether_01 from "../../assets/voice/ch1/ch1_s13_aether_01.mp3?url";
import ch1_s13_aether_die_01 from "../../assets/voice/ch1/ch1_s13_aether_die_01.mp3?url";
import ch1_s13_aether_die_02 from "../../assets/voice/ch1/ch1_s13_aether_die_02.mp3?url";
import ch1_s14_aether_01 from "../../assets/voice/ch1/ch1_s14_aether_01.mp3?url";
import ch1_s15_aether_maya from "../../assets/voice/ch1/ch1_s15_aether_maya.mp3?url";
import ch1_s16_aether_close from "../../assets/voice/ch1/ch1_s16_aether_close.mp3?url";
import ch1_s16_aether_return from "../../assets/voice/ch1/ch1_s16_aether_return.mp3?url";
import ch1_archivist_close from "../../assets/voice/ch1/ch1_archivist_close.mp3?url";

export const VOICE_URLS: Record<string, string> = {
  ch1_s11_aether_01,
  ch1_s11_aether_02,
  ch1_s12a_aether_01,
  ch1_s12a_aether_02,
  ch1_s12a2_aether_01,
  ch1_s12a2_aether_02,
  ch1_s12c_aether_01,
  ch1_s13_aether_01,
  ch1_s13_aether_die_01,
  ch1_s13_aether_die_02,
  ch1_s14_aether_01,
  ch1_s15_aether_maya,
  ch1_s16_aether_close,
  ch1_s16_aether_return,
  ch1_archivist_close,
};
