/**
 * client/src/components/mission-control/missionControlData.test.ts
 *
 * Data-contract guard for the Mission Control dashboard. Phase 1 was static
 * (the data file was hand-maintained); Phase 2 made most of the values
 * build-time-generated by `scripts/generate-mission-control-data.mjs`. This
 * test still guards the contract: every section the page renders must be
 * present, well-formed, and not silently drop back to "unknown" — if a
 * generator field falls back to "unknown" the test fails so the dashboard
 * never lies to the owner about whether the build is fresh.
 *
 * It also covers the StatusLevel union and the size of the workflow list.
 */
import { describe, it, expect } from "vitest";

import { generated } from "./generated";
import { missionControlData, type StatusLevel } from "./missionControlData";

const VALID_STATUSES: StatusLevel[] = [
  "healthy",
  "warning",
  "manual",
  "disabled",
  "unknown",
];

const REQUIRED_HAND_CURATED = [
  "priorities",
  "ownerActions",
] as const;

describe("missionControlData (Phase 2)", () => {
  it("has a generated block with schemaVersion 1 and a generatedAt timestamp", () => {
    expect(generated.schemaVersion).toBe(1);
    expect(typeof generated.generatedAt).toBe("string");
    // ISO 8601 round-trips cleanly through Date().
    expect(Number.isFinite(Date.parse(generated.generatedAt))).toBe(true);
  });

  it("derives the repository head SHA, branch, and commit timestamp", () => {
    // SHA: 7 hex chars (or longer if the generator kept the full one).
    expect(generated.repository.headSha).toMatch(/^[0-9a-f]{7,}$/);
    expect(generated.repository.branch).toBeTruthy();
    expect(
      Number.isFinite(Date.parse(generated.repository.commitTimestampIso)),
    ).toBe(true);
  });

  it("derives the app version and built timestamp from the build environment", () => {
    expect(generated.build.appVersion).toMatch(/^\d+\.\d+\.\d+/);
    expect(generated.build.env).toBeTruthy();
    expect(Number.isFinite(Date.parse(generated.build.builtAtIso))).toBe(true);
  });

  it("derives a deploy mode from the environment", () => {
    expect([
      "local",
      "cloudflare-pages",
      "fly.io",
      "vercel",
    ]).toContain(generated.build.deploy.mode);
  });

  it("derives the workflow list from .github/workflows", () => {
    expect(generated.workflow.workflows.length).toBeGreaterThan(0);
    for (const w of generated.workflow.workflows) {
      expect(VALID_STATUSES).toContain(w.status);
      expect(typeof w.name).toBe("string");
      expect(typeof w.note).toBe("string");
    }
  });

  it("derives the last merged PR from SESSION_LOG.md", () => {
    // PR #272 is the latest known merge on the parent branch; the test
    // accepts anything that looks like a real PR (>0, has a title, merged
    // at a parseable date).
    const pr = generated.workflow.lastMergedPr;
    if (pr.number > 0) {
      expect(pr.title.length).toBeGreaterThan(0);
      if (pr.mergedAt) {
        expect(Number.isFinite(Date.parse(pr.mergedAt))).toBe(true);
      }
    }
  });

  it("merges hand-curated sections (priorities, ownerActions)", () => {
    for (const key of REQUIRED_HAND_CURATED) {
      expect(missionControlData).toHaveProperty(key);
    }
    expect(missionControlData.priorities.activeLane).toBeTruthy();
    expect(missionControlData.ownerActions.length).toBeGreaterThan(0);
  });

  it("exposes the four new Phase 2 sections the page renders", () => {
    // The page now renders these four sections using generated data:
    // repository metadata, workflow status, build info, health indicators.
    expect(missionControlData.repository).toBeTruthy();
    expect(missionControlData.workflow).toBeTruthy();
    expect(missionControlData.build).toBeTruthy();
    expect(missionControlData.health).toBeTruthy();
  });

  it("health indicators use only valid StatusLevels", () => {
    for (const h of missionControlData.health) {
      expect(VALID_STATUSES).toContain(h.status);
    }
  });
});
