import { promises as fs } from "node:fs";
import { existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { createHash } from "node:crypto";

import { composeMusic } from "./elevenlabs";

// scripts/voice/ -> app root is two levels up.
const APP_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..");
const ROOTS = {
  voiceLines: path.join(APP_ROOT, "voice_lines"),
  musicAssets: path.join(APP_ROOT, "src", "assets", "music"),
  archive: path.join(APP_ROOT, "src", "assets", "music", "_archive"),
  generatedIndex: path.join(APP_ROOT, "src", "lib", "music", "index.generated.ts"),
};
// Music is billed by length; cap the total per run so a typo can't drain credits.
const MAX_MS_PER_RUN = 90_000;
const ID_RE = /^[a-z0-9_]+$/;

interface Track {
  id: string;
  length_ms: number;
  loop?: boolean;
  prompt: string;
  notes?: string;
}
interface MusicManifest {
  schema_version: 1;
  model_id: string;
  output_format: string;
  tracks: Track[];
}
interface MusicSidecar {
  id: string;
  model_id: string;
  output_format: string;
  length_ms: number;
  loop: boolean;
  prompt: string;
  content_hash: string;
  generated_at: string;
  version: number;
}

function parseArgs(argv: string[]) {
  const o = { track: undefined as string | undefined, dryRun: false, force: false };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === "--track") o.track = argv[++i];
    else if (a === "--dry-run") o.dryRun = true;
    else if (a === "--force") o.force = true;
  }
  return o;
}

const trackHash = (t: Track, model: string) =>
  createHash("sha256").update(`${t.prompt}${t.length_ms}${model}`, "utf8").digest("hex");

async function atomicWrite(file: string, data: Buffer | string) {
  await fs.mkdir(path.dirname(file), { recursive: true });
  const tmp = path.join(path.dirname(file), `.${path.basename(file)}.tmp`);
  await fs.writeFile(tmp, data);
  await fs.rename(tmp, file);
}

async function writeGeneratedIndex(tracks: Track[]) {
  const pkgDir = path.dirname(ROOTS.generatedIndex);
  const present = tracks.filter((t) => existsSync(path.join(ROOTS.musicAssets, `${t.id}.mp3`)));
  const imports = present
    .map((t) => {
      const rel = path
        .relative(pkgDir, path.join(ROOTS.musicAssets, `${t.id}.mp3`))
        .split(path.sep)
        .join("/");
      return `import ${t.id} from "${rel}?url";`;
    })
    .join("\n");
  const entries = present
    .map((t) => `  ${t.id}: { url: ${t.id}, loop: ${t.loop ? "true" : "false"} },`)
    .join("\n");
  const src =
    `// AUTO-GENERATED by scripts/voice/generate-music.ts — do not edit by hand.\n` +
    `// Run \`pnpm music:generate\` to refresh after changing voice_lines/music.json.\n` +
    `${imports}\n\n` +
    `export interface MusicTrack { url: string; loop: boolean; }\n` +
    `export const MUSIC_TRACKS: Record<string, MusicTrack> = {\n${entries}\n};\n`;
  await atomicWrite(ROOTS.generatedIndex, src);
}

async function run(): Promise<number> {
  const opts = parseArgs(process.argv.slice(2));
  const manifestPath = path.join(ROOTS.voiceLines, "music.json");
  if (!existsSync(manifestPath)) throw new Error(`music.json not found at ${manifestPath}`);
  if (!process.env.ELEVENLABS_API_KEY && !opts.dryRun)
    throw new Error("ELEVENLABS_API_KEY is not set");

  const manifest = JSON.parse(await fs.readFile(manifestPath, "utf8")) as MusicManifest;
  if (manifest.schema_version !== 1) throw new Error("Unexpected music schema_version");

  let tracks = manifest.tracks;
  for (const t of tracks) {
    if (!ID_RE.test(t.id)) throw new Error(`Invalid track id: ${t.id}`);
    if (!t.prompt?.trim()) throw new Error(`Track ${t.id} has empty prompt`);
  }
  if (opts.track) tracks = tracks.filter((t) => t.id === opts.track);
  if (tracks.length === 0) {
    console.error("No tracks matched.");
    return 1;
  }

  const totalMs = tracks.reduce((n, t) => n + t.length_ms, 0);
  if (!opts.dryRun && totalMs > MAX_MS_PER_RUN)
    throw new Error(`Run would generate ${totalMs}ms (> ${MAX_MS_PER_RUN}ms cap). Narrow with --track.`);

  let generated = 0;
  let skipped = 0;
  let failed = 0;
  for (const t of tracks) {
    const hash = trackHash(t, manifest.model_id);
    const mp3Path = path.join(ROOTS.musicAssets, `${t.id}.mp3`);
    const sidecarPath = path.join(ROOTS.musicAssets, `${t.id}.json`);

    let version = 1;
    if (existsSync(sidecarPath)) {
      const prior = JSON.parse(await fs.readFile(sidecarPath, "utf8")) as MusicSidecar;
      if (prior.content_hash === hash && existsSync(mp3Path) && !opts.force) {
        skipped++;
        console.log(`skipped ${t.id} (hash match)`);
        continue;
      }
      version = prior.version + 1;
      if (!opts.dryRun) {
        await fs.mkdir(ROOTS.archive, { recursive: true });
        if (existsSync(mp3Path))
          await fs.rename(mp3Path, path.join(ROOTS.archive, `${t.id}.v${prior.version}.mp3`));
        if (existsSync(sidecarPath))
          await fs.rename(sidecarPath, path.join(ROOTS.archive, `${t.id}.v${prior.version}.json`));
      }
    }

    if (opts.dryRun) {
      console.log(`dry-run ${t.id} (${t.length_ms}ms)`);
      continue;
    }

    try {
      const buf = Buffer.from(
        await composeMusic({
          prompt: t.prompt,
          music_length_ms: t.length_ms,
          model_id: manifest.model_id,
          output_format: manifest.output_format,
        }),
      );
      await atomicWrite(mp3Path, buf);
      const sidecar: MusicSidecar = {
        id: t.id,
        model_id: manifest.model_id,
        output_format: manifest.output_format,
        length_ms: t.length_ms,
        loop: !!t.loop,
        prompt: t.prompt,
        content_hash: hash,
        generated_at: new Date().toISOString(),
        version,
      };
      await atomicWrite(sidecarPath, JSON.stringify(sidecar, null, 2) + "\n");
      generated++;
      console.log(`generated ${t.id} (${buf.byteLength} bytes)`);
    } catch (err) {
      failed++;
      console.error(`FAILED ${t.id}: ${err instanceof Error ? err.message : String(err)}`);
    }
  }

  if (!opts.dryRun) await writeGeneratedIndex(manifest.tracks);
  console.log(`tracks=${tracks.length} generated=${generated} skipped=${skipped} failed=${failed}`);
  return failed === 0 ? 0 : 1;
}

run()
  .then((code) => process.exit(code))
  .catch((err) => {
    console.error(err instanceof Error ? err.message : err);
    process.exit(1);
  });
