import { promises as fs } from "node:fs";
import { existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";
import { randomUUID } from "node:crypto";

import type {
  Manifest,
  Speakers,
  Line,
  Speaker,
  Sidecar,
  LineResult,
  GenerationLog,
} from "./types";
import { contentHash } from "./hash";
import { synthesize } from "./elevenlabs";

// scripts/voice/ -> app root is two levels up. Paths are anchored to this file,
// so the generator works regardless of the caller's cwd.
const APP_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..");
const ROOTS = {
  voiceLines: path.join(APP_ROOT, "voice_lines"),
  voiceAssets: path.join(APP_ROOT, "src", "assets", "voice"),
  archive: path.join(APP_ROOT, "src", "assets", "voice", "_archive"),
  generatedIndex: path.join(APP_ROOT, "src", "lib", "voice", "index.generated.ts"),
};
const MAX_CHARS_PER_RUN = 50_000;
const LINE_ID_RE = /^[a-z0-9_]+$/;

interface Options {
  chapter?: string;
  line?: string;
  dryRun: boolean;
  force: boolean;
}

function parseArgs(argv: string[]): Options {
  const o: Options = { dryRun: false, force: false };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === "--chapter") o.chapter = argv[++i];
    else if (a === "--line") o.line = argv[++i];
    else if (a === "--dry-run") o.dryRun = true;
    else if (a === "--force") o.force = true;
  }
  return o;
}

async function readJson<T>(p: string): Promise<T> {
  return JSON.parse(await fs.readFile(p, "utf8")) as T;
}

function validate(manifest: Manifest, speakers: Speakers): void {
  if (manifest.schema_version !== 1)
    throw new Error(`Unexpected schema_version: ${manifest.schema_version}`);
  if (!Array.isArray(manifest.lines)) throw new Error("manifest.lines must be an array");
  const seen = new Set<string>();
  for (const l of manifest.lines) {
    if (!LINE_ID_RE.test(l.id))
      throw new Error(`Invalid line id (must match /^[a-z0-9_]+$/): ${l.id}`);
    if (seen.has(l.id)) throw new Error(`Duplicate line id: ${l.id}`);
    seen.add(l.id);
    if (!speakers[l.speaker])
      throw new Error(`Line ${l.id} references unknown speaker '${l.speaker}'`);
    if (!l.text?.trim()) throw new Error(`Line ${l.id} has empty text`);
  }
}

async function atomicWrite(file: string, data: Buffer | string): Promise<void> {
  await fs.mkdir(path.dirname(file), { recursive: true });
  const tmp = path.join(path.dirname(file), `.${path.basename(file)}.tmp`);
  await fs.writeFile(tmp, data);
  await fs.rename(tmp, file);
}

function probeDuration(mp3: string): number | null {
  const r = spawnSync(
    "ffprobe",
    ["-v", "error", "-show_entries", "format=duration", "-of", "csv=p=0", mp3],
    { encoding: "utf8" },
  );
  if (r.status !== 0 || !r.stdout) return null;
  const n = Number.parseFloat(r.stdout.trim());
  return Number.isFinite(n) ? n : null;
}

/**
 * Emit a committed, Vite-native lookup module. Each clip is imported with the
 * `?url` suffix (Vite resolves it to a bundled, content-hashed asset URL), so
 * the runtime never touches the filesystem. Only lines whose MP3 actually
 * exists on disk are emitted, so a partial generation never breaks the build.
 */
async function writeGeneratedIndex(lines: Line[]): Promise<void> {
  const pkgDir = path.dirname(ROOTS.generatedIndex);
  const present = lines.filter((l) =>
    existsSync(path.join(ROOTS.voiceAssets, l.chapter, `${l.id}.mp3`)),
  );
  const imports = present
    .map((l) => {
      const rel = path
        .relative(pkgDir, path.join(ROOTS.voiceAssets, l.chapter, `${l.id}.mp3`))
        .split(path.sep)
        .join("/");
      return `import ${l.id} from "${rel}?url";`;
    })
    .join("\n");
  const entries = present.map((l) => `  ${l.id},`).join("\n");
  const src =
    `// AUTO-GENERATED by scripts/voice/generate-all.ts — do not edit by hand.\n` +
    `// Run \`pnpm voice:generate\` to refresh after changing the manifest.\n` +
    `${imports}\n\n` +
    `export const VOICE_URLS: Record<string, string> = {\n${entries}\n};\n`;
  await atomicWrite(ROOTS.generatedIndex, src);
}

function resolveSpeaker(line: Line, speakers: Speakers): Speaker {
  return speakers[line.speaker];
}

async function run(): Promise<number> {
  const opts = parseArgs(process.argv.slice(2));
  if (!existsSync(ROOTS.voiceLines))
    throw new Error(`voice_lines not found at ${ROOTS.voiceLines}`);
  if (!process.env.ELEVENLABS_API_KEY && !opts.dryRun)
    throw new Error("ELEVENLABS_API_KEY is not set");

  const manifest = await readJson<Manifest>(path.join(ROOTS.voiceLines, "manifest.json"));
  const speakers = await readJson<Speakers>(path.join(ROOTS.voiceLines, "speakers.json"));
  validate(manifest, speakers);

  let lines = manifest.lines;
  if (opts.chapter) lines = lines.filter((l) => l.chapter === opts.chapter);
  if (opts.line) lines = lines.filter((l) => l.id === opts.line);
  if (lines.length === 0) {
    console.error("No lines matched the given filters.");
    return 1;
  }

  // Cost guard: refuse to (re)generate beyond the cap. Skips don't count.
  const totalChars = lines.reduce((n, l) => n + l.text.length, 0);
  if (!opts.dryRun && totalChars > MAX_CHARS_PER_RUN) {
    throw new Error(
      `Run would synthesize ${totalChars} chars (> ${MAX_CHARS_PER_RUN} cap). Narrow with --line/--chapter.`,
    );
  }

  const results: LineResult[] = [];
  for (const line of lines) {
    const speaker = resolveSpeaker(line, speakers);
    const hash = contentHash(line.text, speaker);
    const dir = path.join(ROOTS.voiceAssets, line.chapter);
    const mp3Path = path.join(dir, `${line.id}.mp3`);
    const sidecarPath = path.join(dir, `${line.id}.json`);

    let version = 1;
    let priorStatus: LineResult["status"] = "generated";
    if (existsSync(sidecarPath)) {
      const prior = await readJson<Sidecar>(sidecarPath);
      if (prior.content_hash === hash && existsSync(mp3Path) && !opts.force) {
        results.push({ line_id: line.id, status: "skipped", reason: "hash match", path: mp3Path });
        continue;
      }
      version = prior.version + 1;
      priorStatus = "archived_and_regenerated";
      if (!opts.dryRun) {
        await fs.mkdir(ROOTS.archive, { recursive: true });
        if (existsSync(mp3Path))
          await fs.rename(mp3Path, path.join(ROOTS.archive, `${line.id}.v${prior.version}.mp3`));
        if (existsSync(sidecarPath))
          await fs.rename(
            sidecarPath,
            path.join(ROOTS.archive, `${line.id}.v${prior.version}.json`),
          );
      }
    }

    if (opts.dryRun) {
      results.push({ line_id: line.id, status: priorStatus, reason: "dry-run", path: mp3Path });
      continue;
    }

    try {
      const buf = Buffer.from(await synthesize(line.text, speaker));
      await atomicWrite(mp3Path, buf);
      const sidecar: Sidecar = {
        line_id: line.id,
        chapter: line.chapter,
        speaker: line.speaker,
        voice_id: speaker.voice_id,
        voice_name: speaker.voice_name,
        model_id: speaker.model_id,
        voice_settings: speaker.voice_settings,
        text: line.text,
        content_hash: hash,
        generated_at: new Date().toISOString(),
        duration_seconds: probeDuration(mp3Path),
        version,
      };
      await atomicWrite(sidecarPath, JSON.stringify(sidecar, null, 2) + "\n");
      results.push({ line_id: line.id, status: priorStatus, bytes: buf.byteLength, path: mp3Path });
    } catch (err) {
      results.push({
        line_id: line.id,
        status: "failed",
        reason: err instanceof Error ? err.message : String(err),
      });
    }
  }

  const tally = (s: LineResult["status"]) => results.filter((r) => r.status === s).length;
  const log: GenerationLog = {
    run_id: randomUUID(),
    started_at: new Date().toISOString(),
    finished_at: new Date().toISOString(),
    total: results.length,
    generated: tally("generated"),
    skipped: tally("skipped"),
    archived_and_regenerated: tally("archived_and_regenerated"),
    failed: tally("failed"),
    results,
  };
  if (!opts.dryRun) {
    await atomicWrite(
      path.join(ROOTS.voiceLines, "generation.log.json"),
      JSON.stringify(log, null, 2) + "\n",
    );
    await writeGeneratedIndex(manifest.lines);
  }

  console.log(
    `total=${log.total} generated=${log.generated} skipped=${log.skipped} archived=${log.archived_and_regenerated} failed=${log.failed}`,
  );
  for (const r of results.filter((r) => r.status === "failed")) {
    console.error(`  FAILED ${r.line_id}: ${r.reason}`);
  }
  return log.failed === 0 ? 0 : 1;
}

run()
  .then((code) => process.exit(code))
  .catch((err) => {
    console.error(err instanceof Error ? err.message : err);
    process.exit(1);
  });
