// AUTO-GENERATED by scripts/voice/generate-music.ts — do not edit by hand.
// Run `pnpm music:generate` to refresh after changing voice_lines/music.json.
import title_intro from "../../assets/music/title_intro.mp3?url";

export interface MusicTrack { url: string; loop: boolean; }
export const MUSIC_TRACKS: Record<string, MusicTrack> = {
  title_intro: { url: title_intro, loop: false },
};
